language:
  - python
python:
  - "2.7"
# command to install dependencies
install:
    # command to run tests
  - pip install colored --upgrade
  - pip install coverage
  - pip install coveralls  
script:
  - coverage run test_rpn.py
after_success:
  - coveralls   
